version: '3.9'
services:

  nginx:
    container_name: gateway
    image: nginx:latest
    networks:
      hserver
    ports:
      - "80:80"
    volumes:
      - nginx-volume: /etc/nginx/conf.d
    restart: always

  volume-manager:
    image: alpine:latest
    container_name: manager
    networks:
      hserver
    volumes:
      - nginx-volume: /data/nginx
    restart: always

volumes:
  nginx-volume

networks:
  hserver:
  external: true


